version: '3.9'
services:
  db:
    image: mysql:8
    container_name: test
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: test
    ports:
      - "3309:3306"
    networks:
      - my_network
  app:
    image: demo  # Docker 이미지로 설정
    container_name: demo-container
    ports:
      - "8082:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/test
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge